# Match report

## Introduction
This notebook aims to analyze a match using data-driven methods, exploring key player statistics and overall game dynamics. It also introduces a simple player scoring system, assigning points based on individual performance to enable clear comparison and ranking.

## Import dependencies
First of all, we will import our dependencies. We will use `Pandas` for DataFrame manipulation and `Matplotlib` for data visualization.

In [90]:
import pandas as pd
import matplotlib.pyplot as plt

## Import data, clean and prepare
The objective of this section is to prepare two datasets: one containing the overall actions of both teams, and another focused on individual player data for detailed analysis.

For this notebook, we will use data collected from the recording of the league match between FC Barcelona and Real Madrid during the 2024/2025 season. The data was manually captured using `log_data.py` and saved in the file `barça_madrid_2425.csv`.

This file stores the actions of each player from one team, as well as the overall actions of the opposing team. It is important to note that when an action belongs to the opponent, the system assigns the value "Equipo rival" to the `player` field and "Rival" to the `position` field. Therefore, only a general analysis of the opposing team’s actions can be performed.

Let's have a look on it.

In [91]:
csv_file = "../data/barça_madrid_2425.csv"
df = pd.read_csv(csv_file)
df.head()

             timestamp        player   action position
0  2026-04-24T13:42:56  Equipo rival     Pase    Rival
1  2026-04-24T13:43:00  Equipo rival     Pase    Rival
2  2026-04-24T13:43:13  Equipo rival     Pase    Rival
3  2026-04-24T13:43:25  Equipo rival     Pase    Rival
4  2026-04-24T13:44:01  Equipo rival  Despeje    Rival

For our analysis, the `timestamp` column is not useful, as it only indicates the moment when the data was captured. For that reason, we will remove it.

In [92]:
df = df.drop(columns=["timestamp"])
df.head()

         player   action position
0  Equipo rival     Pase    Rival
1  Equipo rival     Pase    Rival
2  Equipo rival     Pase    Rival
3  Equipo rival     Pase    Rival
4  Equipo rival  Despeje    Rival

Now we will standardize the data by converting everything to lowercase. Player names will be kept unchanged to preserve their formatting.

In [93]:
df["action"] = df["action"].str.strip().str.lower()
df["position"] = df["position"].str.strip().str.lower()
df.head()

         player   action position
0  Equipo rival     pase    rival
1  Equipo rival     pase    rival
2  Equipo rival     pase    rival
3  Equipo rival     pase    rival
4  Equipo rival  despeje    rival

Finally, we will rename "Equipo rival" to "rival".

In [94]:
df["player"] = df["player"].replace("Equipo rival", "rival")
df.head()

  player   action position
0  rival     pase    rival
1  rival     pase    rival
2  rival     pase    rival
3  rival     pase    rival
4  rival  despeje    rival

Now we will create a DataFrame with the overall data from both teams, without going into player-level details.

Using the DataFrame created from the `barça_madrid_2425.csv` file, we will count the number of actions per team.

In [ ]:
teams_df = pd.DataFrame() 

actions = df["action"].unique()
teams = ["FC Barcelona", "Real Madrid"]

teams_df["team"] = teams
for action in actions:
    teams_df[action] = 0

counts = df.groupby(["player", "action"]).size()
for (player, action), count in counts.items():
    if player == "rival":
        teams_df.loc[teams_df["team"] == "Real Madrid", action] += count
    else:
        teams_df.loc[teams_df["team"] == "FC Barcelona", action] += count

teams_df.head()

,team,pase,despeje,falta cometida,pase errado,perdida,intercepcion,falta recibida,penalti cometido,penalti recibido,gol,recuperacion,regate,tiro a puerta,parada,tiro,blocaje,tarjeta amarilla
0,FC Barcelona,138,2,5,23,15,7,5,1,0,2,16,6,5,0,3,0,0
1,Real Madrid,66,19,6,11,9,7,5,0,1,2,11,3,1,3,0,1,1

Now we will create the player-level DataFrame following a similar process as before.

In [105]:
players_df = pd.DataFrame()

players_df["player"] = df["player"].unique()

# remove rival data we only want player data
players_df = players_df[players_df["player"] != "rival"]

for action in actions:
    players_df[action] = 0

counts = df.groupby(["player", "action"]).size()
for (player, action), count in counts.items():
    if player != "rival":
        players_df.loc[players_df["player"] == player, action] += count

players_df.head()

,player,pase,despeje,falta cometida,pase errado,perdida,intercepcion,falta recibida,penalti cometido,penalti recibido,gol,recuperacion,regate,tiro a puerta,parada,tiro,blocaje,tarjeta amarilla
1,Raphinha,13,0,0,6,3,0,0,0,0,0,1,0,0,0,0,0,0
2,Eric Garcia,12,0,0,2,0,1,0,0,0,1,0,1,2,0,0,0,0
3,Ferran Torres,5,0,0,0,1,0,1,0,0,0,0,2,0,0,1,0,0
4,Cubarsi,8,1,1,0,0,4,0,0,0,0,1,0,0,0,0,0,0
5,Dani Olmo,9,0,2,4,3,0,0,0,0,0,0,0,0,0,0,0,0